Vagrant.configure("2") do |config|
  

    config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	web01.vm.network "private_network", ip: "192.168.40.11"
	web01.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
	vb.cpus = 1
	web01.vm.provision "shell", inline: <<-SHELL
     sudo apt update -y
	 sudo apt install apache2 wget unzip -y
	 systemctl start apache2
	 systemctl enable apache2
	 cd /tmp/
	 wget https://www.tooplate.com/zip-templates/2121_wave_cafe.zip 
	 unzip -o 2121_wave_cafe.zip
	 cp -r 2121_wave_cafe/* /var/www/html/
	 systemctl restart apache2	  
   SHELL
	
  end
end
	config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
	db01.vm.network "private_network", ip: "192.168.40.12"
	db01.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
	vb.cpus = 1
	db01.vm.provision "shell", inline: <<-SHELL
	sudo yum update -y
	sudo yum install mariadb-server -y
    sudo systemctl start mariadb 
	sudo systemctl enable mariadb
	
	mysql -u root -e 'CREATE DATABASE wordpress;'
	mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
	mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'
	mysql -u root -e 'FLUSH PRIVILEGES;'
	
	sudo systemctl restart mariadb
	
   SHELL
  end
end
end
